name: archify
description: A CLI tool for generating clean architecture structure in Flutter projects.
version: 1.0.5
homepage: https://github.com/ashiq-dev-codes/archify
repository: https://github.com/ashiq-dev-codes/archify.git
issue_tracker: https://github.com/ashiq-dev-codes/archify/issues

environment:
  sdk: ^3.8.1

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.25.6
  lints: ^6.0.0

executables:
  archify: archify